- hosts: all
  vars:
       - docker_url: 'https://download.docker.com/linux/centos/7/x86_64/stable'
  tasks:
   - file:
      path: /dvd1
      state: directory

   - mount:
      src: /dev/cdrom
      path: /dvd1
      state: mounted
      fstype: "iso9660"
    
   - yum_repository:
      baseurl: "/dvd1/AppStream"
      name: "dvd"
      description: "Yum first DVD"
      gpgcheck: "no"

   - yum_repository:
      baseurl: "/dvd1/BaseOS"
      name: "dvd2"
      description: "Yum second DVD"
      gpgcheck: "no"

   - yum_repository:
      baseurl: "{{ docker_url }}"
      name: "docker"
      description: "yum docker DVD"
      gpgcheck: "no"

   - command: "yum install docker-ce --nobest -y"
      name: "docker-ce-18.09.1-3.el7.x86_64"
      state: present

   - service:
      name: "docker"
      state: started
      enabled: yes

   - pip:
      name: "docker"

   - docker_image:
      name: "httpd"
      source: pull
   - docker_container:
      name: "myOS"
      image: "httpd"
      state: started
      exposed_ports: 80
      detach: yes
      ports: "80"
      volumes: "/var/www/html:/usr/local/apache2/htdoc/"


   - copy:
      dest: "/var/www/html/my.html"
      content: "This is webpage on the top of docker"

   - firewalld: 
      port: "80/tcp"
      state: enabled
      permanent: yes
      immediate: yes
